[theme]
primaryColor             = "#c478d2"
backgroundColor          = "#090614"
secondaryBackgroundColor = "#100d1e"
textColor                = "#e4dff0"

[[theme.fontFaces]]
family = "DM Serif Display"
url    = "./static/DMSerifDisplay-Regular.ttf"
style  = "normal"

[[theme.fontFaces]]
family = "DM Serif Display"
url    = "./static/DMSerifDisplay-Italic.ttf"
style  = "italic"

[[theme.fontFaces]]
family      = "DM Sans"
url         = "./static/DMSans.ttf"
weightRange = "100 900"

[server]
enableStaticServing = true
